// <auto-generated />
using JobTaskByMofijul.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobTaskByMofijul.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250721044016_Seed Data")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobTaskByMofijul.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            Email = "alice@example.com",
                            Name = "Alice",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Age = 30,
                            Email = "bob@example.com",
                            Name = "Bob",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            Email = "charlie@example.com",
                            Name = "Charlie",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Age = 27,
                            Email = "david@example.com",
                            Name = "David",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Age = 29,
                            Email = "eve@example.com",
                            Name = "Eve",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 6,
                            Age = 31,
                            Email = "frank@example.com",
                            Name = "Frank",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            Age = 26,
                            Email = "grace@example.com",
                            Name = "Grace",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 8,
                            Age = 28,
                            Email = "hank@example.com",
                            Name = "Hank",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 9,
                            Age = 24,
                            Email = "ivy@example.com",
                            Name = "Ivy",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 10,
                            Age = 35,
                            Email = "jack@example.com",
                            Name = "Jack",
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
